title: "Nkosilathi Tauro"
email: nkosilati23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An open-minded, self-motivated individual, who enjoys the science behind things, (I'm fascinated by the ways things work) and the great outdoors. I am eager to be challenged in order to grow and improve my communication and professional skills.
baseurl: "/" 
url: "/mlh-portfolio" 
twitter_username: ""
github_username:  nkosi-tauro

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg